### ISSUE TITLE
Wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by 0xChupaCabra** [bttcprotocol/delivery#71]
when synchronizing delivery i get this error, running latest vevrsion

```
I[2023-09-21|20:29:13.135] Executed block                               module=state height=8603520 validTxs=0 invalidTxs=0
I[2023-09-21|20:29:13.149] Committed state                              module=state height=8603520 txs=0 appHash=83A6D4C05D58D063A67A0ADCBDEC9C889926184EDC07CD8046CF6B204AE93F51
I[2023-09-21|20:29:13.167] Executed block                               module=state height=8603521 validTxs=0 invalidTxs=0
I[2023-09-21|20:29:13.176] Committed state                              module=state height=8603521 txs=0 appHash=83A6D4C05D58D063A67A0ADCBDEC9C889926184EDC07CD8046CF6B204AE93F51
I[2023-09-21|20:29:13.193] Executed block                               module=state height=8603522 validTxs=0 invalidTxs=0
I[2023-09-21|20:29:13.203] Committed state                              module=state height=8603522 txs=0 appHash=1F6C7E4A140DFEA221DB371F1E0D77EDF79EC9F35B8314C19DA32EC8231D9E36
panic: Failed to process committed block (8603523:B3EEF74D8AB8E9CFD3518572CC9ED57705B9A3910C2EE211D7CCCF06F5079326): Wrong Block.Header.AppHash.  Expected 1F6C7E4A140DFEA221DB371F1E0D77EDF79EC9F35B8314C19DA32EC8231D9E36, got EBFC1B856BFBA094E77776522679764A3AF7B0B6B8ED1AFC4E7E9F7EFBB26FF3

goroutine 43 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0016e6000)
        /home/stepollo/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220803122020-9c20f6000900/blockchain/v0/reactor.go:344 +0x10a5
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /home/stepollo/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220803122020-9c20f6000900/blockchain/v0/reactor.go:118 +0x7a
```

**Comment by 0xChupaCabra** [comment]
i did try to resync mang times from scratch but no luck. i then gave up but our team would like to run a node

**Comment by bladehan1** [comment]
Clear the data store and resync with the latest version
